base/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
        openapi.Info(
            title="API Documentation",
            default_version='v1',
            description="Your API description",
            terms_of_service="https://www.example.com/policies/terms/",
            contact=openapi.Contact(email="contact@example.com"),
            license=openapi.License(name="BSD License"),
        ),
        public=True,
        permission_classes=(permissions.AllowAny,),
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('weather/', include('weather.urls', namespace='weather')),
    # swagger
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserLoginView, UserRegistrationCreateView, logaut

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('registration/', UserRegistrationCreateView.as_view(), name='registration'),
    path('logout/', logaut, name='logout'),
]

weather/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from weather.apps import WeatherConfig
from weather.views import index, WeatherDeleteView, WeatherListAPIView, WeatherRetrieveAPIView

app_name = WeatherConfig.name

urlpatterns = [
    path('weather/', index, name='weather'),
    path('delete/<int:pk>/', WeatherDeleteView.as_view(), name='delete_weather'),
    # Token
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # API
    path('list/', WeatherListAPIView.as_view(), name='list'),
    path('detail/<int:pk>', WeatherRetrieveAPIView.as_view(), name='detail'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


NULABLLE = {'null': True, 'blank': True}


class User(AbstractUser):
    """
    Расширяет базовую модель таблицы БД Django 'auth_user'
    добавление "image", на выходе имеем таблицу "user_user"
    """
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=30, verbose_name='Телефон', **NULABLLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULABLLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

weather/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class WeatherModel(models.Model):
    """
    Модель для хранения информации о погоде
    """
    city = models.CharField(max_length=100, verbose_name='Город')
    temperature = models.FloatField(verbose_name='Температура', **NULLABLE)
    icon = models.CharField(max_length=20, verbose_name='Иконка погоды', **NULLABLE)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return self.city

    class Meta:
        verbose_name = 'Погода'
        verbose_name_plural = 'Погода'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.common import StyleFormMixin
from users.models import User


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    """
    Класс для работы с формой "UserLoginForm"
    """
    class Meta:
        model = User
        fields = ('email', 'password')


class UserRegistrationForm(StyleFormMixin, UserCreationForm):
    """
    Класс для работы с формой "UserRegistrationForm"
    """

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

weather/forms.py
from django.forms import ModelForm, TextInput

from weather.models import WeatherModel


class CityForm(ModelForm):
    """
    Класс для работы с формой "CityForm"
    """
    class Meta:
        model = WeatherModel
        fields = ('city',)
        widgets = {
            'city': TextInput(attrs={'class': 'form-control',
                                     'city': 'city',
                                     'id': 'city',
                                     'placeholder': 'Введите название города',
                                     })}

users/views.py
from django.contrib import auth
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from users.common import TitleMixin
from users.forms import UserLoginForm, UserRegistrationForm
from users.models import User


class UserLoginView(TitleMixin, LoginView):
    """
    Класс для работы с формой "UserLoginForm"
    Отображение полей при логине пользователя и админ панели если пользователь
    является суперпользователем
    """
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Авторизация'

    def get_success_url(self):
        return reverse_lazy('weather:weather')


class UserRegistrationCreateView(TitleMixin, CreateView):
    """
    Класс для работы с формой "UserRegistrationForm"
    Отображение полей при регистрации пользователя и админ панели если пользователь
    является суперпользователем
    """
    model = User
    form_class = UserRegistrationForm
    title = 'Регистрация'

    def form_valid(self, form):

        user = form.save()
        user.is_active = True
        user.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:login')


def logaut(request):
    """
    Функция вида logaut
    Отображение полей при регистрации пользователя и админ панели если пользователь
    является суперпользователем
    :return: HttpResponseRedirect(reverse('index'))
    """
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login'))

weather/views.py
import os
import requests
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from users.common import TitleMixin
from weather.forms import CityForm

from weather.models import WeatherModel
from weather.paginators import Paginator
from weather.permissions import IsOwner
from weather.serializers import WeatherSerializer


@login_required
def index(request):
    """
    Главная страница приложения
    """

    apy_key = os.getenv('API_KEY')
    if request.method == 'POST':
        result = requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={request.POST.get('city')}"
                              f"&units=metric&appid={apy_key}").json()
        res = WeatherModel.objects.create(owner=request.user, city=request.POST.get('city'),
                                          temperature=result['main']['temp'], icon=result['weather'][0]['icon'])
        res.save()

    form = CityForm()

    cities = WeatherModel.objects.all()

    context = {
        'all_info': cities,
        'form': form,

    }
    return render(request, 'weather/index.html', context, )


class WeatherDeleteView(DeleteView, TitleMixin):
    """
    Класс для удаления погодных данных города
    """
    model = WeatherModel
    title = 'Удаление города'

    def get_success_url(self):
        return reverse_lazy('weather:weather')


class WeatherListAPIView(generics.ListAPIView):
    """
    API для получения списка запросов погоды всех пользователей
    """
    serializer_class = WeatherSerializer
    queryset = WeatherModel.objects.all()
    permission_classes = (IsAuthenticated,)
    pagination_class = Paginator


class WeatherRetrieveAPIView(generics.RetrieveAPIView):
    """
    API для получения одного клиента с его запросами погоды
    """
    serializer_class = WeatherSerializer
    queryset = WeatherModel.objects.all()
    permission_classes = (IsAuthenticated, IsOwner)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/all.min.js' %}"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} {% endblock %}
    </div>
</div>
<script src="{% static 'js/slim.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Привет</title>
</head>
<body>
<h4>Привет</h4>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.non_field_errors %}
                <div class="alert
                {% if messages %} alert-success {% else %} alert-warning {% endif %}
                 alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}

                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'users:login' %}" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">

                                <input class="btn btn-primary" type="submit" value="Авторизоваться">
                            </div>

                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">

                                    <div class="col-md-12">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:login' %}">
                                    Уже есть аккаунт? Авторизоваться
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

weather/templates/includes/inc_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'weather:weather' %}">Weather</a>
        <div class="dropdown text-end">

            <ul class="dropdown-menu text-small">

            </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Контакты </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Отзывы</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_superuser or user.is_staff %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                        <li>

                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

weather/templates/weather/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}

</head>
<body>
{% include 'includes/inc_menu.html' %}
{% block title %}{% endblock %}
<div class="container">

    {% block container %}{% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                YourStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'js/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
</body>
</html>

weather/templates/weather/index.html
{% extends 'weather/base.html' %}
{% load static %}

{% block title %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6 m-3">Weather</h1>
    <p class="lead">Прогноз погоды в любое время, в любом месте</p>
    <p class="lead">Мы рады что <b>вы</b> с нами!</p>
</div>
{% endblock %}

{% block container %}

<div class="container mt-5">
        <div class="row">
            <div class="col-5">
                <h1>Погода в вашем городе</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.city }}

                    <input type="submit" name="send" value="Узнать" class="mt-2 btn btn-danger">
                </form>
            </div>
<div class="col-5 offset-2">
                <h1>Информация</h1>

                {% for city in all_info %}
                {% if user == city.owner or user.is_superuser %}
                <div class="alert alert-info">
                    <div class="row">
                        <div class="col-9">
                            <b>Город:</b> {{ city.city }}<br>
                            <b>Температура:</b> {{ city.temperature }}<sup>o</sup><br>
                        </div>
                        <div class="col-2 offset-1">
                            <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Картинка погоды">
                        </div>
                    </div>
                    <a class="btn btn-outline-danger btn-block" href="{% url 'weather:delete_weather' city.id %}">
                                Удалить
                            </a>
                </div>
{% endif %}
                {% endfor %}

            </div>
        </div>

</div>



{% endblock %}

weather/templates/weather/weathermodel_confirm_delete.html
{% extends 'weather/base.html' %}
{% block container %}

<div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalChoice">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-3 shadow">
      <div class="modal-body p-4 text-center">
        <h5 class="mb-0">Удалить?</h5>
        <p class="mb-0">Вы уверены что хотите удалить город ({{ object.city }})?</p>
      </div>
<form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
      <div class="modal-footer flex-nowrap p-0">

        <button type="submit" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end"><strong>Да</strong></button>
        <a href="{% url 'weather:weather' %}" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" >Отмена</a>

      </div>
    </form>
    </div>
  </div>
</div>
{% endblock %}